package Grafica.app.gui;

import java.awt.Graphics;

/**
 *
 * @author JessicaRamsa
 */
public class Principal extends javax.swing.JFrame {
    private int mouseX;
    private int mouseY;
    private int xAnterior, yAnterior;
    private int xInicio, yInicio, xFin, yFin;
    private boolean inicio = true;
    // 0 - recta, 1 - rectangulo, 2 - ovalo
    private int mode;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        panelCentro.update(this.getGraphics());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSur = new javax.swing.JPanel();
        txtCursorx = new javax.swing.JTextField();
        txtCursory = new javax.swing.JTextField();
        lblCursorx = new javax.swing.JLabel();
        lblCursory = new javax.swing.JLabel();
        panelOeste = new javax.swing.JPanel();
        btnClean = new javax.swing.JButton();
        panelEste = new javax.swing.JPanel();
        btnLine = new javax.swing.JButton();
        btnOval = new javax.swing.JButton();
        btnRect = new javax.swing.JButton();
        btnLiga = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba");
        setMinimumSize(new java.awt.Dimension(200, 200));

        panelSur.setBackground(new java.awt.Color(0, 153, 102));

        lblCursorx.setText("X");

        lblCursory.setText("Y");

        javax.swing.GroupLayout panelSurLayout = new javax.swing.GroupLayout(panelSur);
        panelSur.setLayout(panelSurLayout);
        panelSurLayout.setHorizontalGroup(
            panelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSurLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblCursorx, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCursorx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblCursory, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCursory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        panelSurLayout.setVerticalGroup(
            panelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSurLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCursory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCursory)
                    .addComponent(txtCursorx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCursorx))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(panelSur, java.awt.BorderLayout.PAGE_END);

        panelOeste.setBackground(new java.awt.Color(0, 102, 102));

        btnClean.setText("Limpiar");
        btnClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCleanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOesteLayout = new javax.swing.GroupLayout(panelOeste);
        panelOeste.setLayout(panelOesteLayout);
        panelOesteLayout.setHorizontalGroup(
            panelOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOesteLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnClean)
                .addContainerGap())
        );
        panelOesteLayout.setVerticalGroup(
            panelOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOesteLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnClean)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(panelOeste, java.awt.BorderLayout.LINE_END);

        panelEste.setBackground(new java.awt.Color(0, 102, 102));

        btnLine.setText("Dibujar línea");
        btnLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLineMousePressed(evt);
            }
        });

        btnOval.setText("Ovalo");
        btnOval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOvalMousePressed(evt);
            }
        });

        btnRect.setText("Rectangulo");
        btnRect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRectMousePressed(evt);
            }
        });

        btnLiga.setText("Efecto liga");
        btnLiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLigaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelEsteLayout = new javax.swing.GroupLayout(panelEste);
        panelEste.setLayout(panelEsteLayout);
        panelEsteLayout.setHorizontalGroup(
            panelEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEsteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLine))
                    .addComponent(btnRect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEsteLayout.setVerticalGroup(
            panelEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnLine)
                .addGap(18, 18, 18)
                .addComponent(btnRect)
                .addGap(18, 18, 18)
                .addComponent(btnOval)
                .addGap(18, 18, 18)
                .addComponent(btnLiga)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(panelEste, java.awt.BorderLayout.LINE_START);

        panelCentro.setBorder(new javax.swing.border.MatteBorder(null));
        panelCentro.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panelCentro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelCentroMouseMoved(evt);
            }
        });
        panelCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCentroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCentroLayout = new javax.swing.GroupLayout(panelCentro);
        panelCentro.setLayout(panelCentroLayout);
        panelCentroLayout.setHorizontalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        panelCentroLayout.setVerticalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        menu.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setText("File");
        menu.add(jMenu1);

        jMenu2.setText("Edit");
        menu.add(jMenu2);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelCentroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCentroMouseMoved
        Graphics g = this.panelCentro.getGraphics();
        mouseX = evt.getX();
        mouseY = evt.getY();
        
        this.txtCursorx.setText(Integer.toString(mouseX));
        this.txtCursory.setText(Integer.toString(mouseY));
        
        if (mode == 3 && inicio) {
            g.clearRect(xInicio, yInicio, xAnterior, yAnterior);
            xAnterior = mouseX;
            yAnterior = mouseY;
            g.drawLine(xInicio, yInicio, xAnterior, yAnterior);
        }
    }//GEN-LAST:event_panelCentroMouseMoved

    private void panelCentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCentroMouseClicked
        Graphics g = this.panelCentro.getGraphics();
        
        if (inicio) {
            xInicio = evt.getX();
            yInicio = evt.getY();
            inicio = false;
        } else {
            xFin = evt.getX();
            yFin = evt.getY();
            inicio = true;
            dibujaFigura(g);
        }
    }//GEN-LAST:event_panelCentroMouseClicked

    private void btnCleanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanMousePressed
        panelCentro.removeAll();;
        panelCentro.repaint();
        inicio = true;
        xInicio = evt.getX();
        xInicio = evt.getX();
        xFin = evt.getX();
        yFin = evt.getY();
    }//GEN-LAST:event_btnCleanMousePressed

    private void btnLineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLineMousePressed
        mode = 0;
    }//GEN-LAST:event_btnLineMousePressed

    private void btnRectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRectMousePressed
        mode = 1;
    }//GEN-LAST:event_btnRectMousePressed

    private void btnOvalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOvalMousePressed
        mode = 2;
    }//GEN-LAST:event_btnOvalMousePressed

    private void btnLigaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLigaMousePressed
        mode = 3;
    }//GEN-LAST:event_btnLigaMousePressed

    public void dibujaFigura(Graphics g) {
        int ancho = Math.abs(xFin - xInicio);
        int alto = Math.abs(yFin - yFin);
        
        switch(mode) {
            case 0:
                g.drawLine(xInicio, yInicio, xFin, yFin);
                break;
            case 1:
                g.drawRect(xInicio, yInicio, ancho, alto);
                break;
            case 2:
                g.drawOval(xInicio, yInicio, ancho, alto);
                break;
            case 3:
                g.drawLine(xInicio, yInicio, xFin, yFin);
                break;
            default:
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnLiga;
    private javax.swing.JButton btnLine;
    private javax.swing.JButton btnOval;
    private javax.swing.JButton btnRect;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lblCursorx;
    private javax.swing.JLabel lblCursory;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelEste;
    private javax.swing.JPanel panelOeste;
    private javax.swing.JPanel panelSur;
    private javax.swing.JTextField txtCursorx;
    private javax.swing.JTextField txtCursory;
    // End of variables declaration//GEN-END:variables
}
